# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rmb', models.DecimalField(decimal_places=2, max_digits=8)),
                ('aud', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exchange Record',
                'ordering': ('-date',),
            },
        ),
    ]
