# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese', models.CharField(db_index=True, max_length=200, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese', models.CharField(db_index=True, max_length=200, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('reference', models.URLField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('price_rmb', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Selling Price RMB')),
                ('price_aud', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Selling Price AUD')),
                ('expense_aud', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Buying Cost AUD')),
                ('expense_rmb', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Buying Cost RMB')),
                ('weight', models.PositiveIntegerField(blank=True, default=0, verbose_name='Weight (g)')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to=shop.models.Product.image_path)),
                ('ico', models.ImageField(blank=True, upload_to=shop.models.Product.ico_path)),
                ('category', models.ManyToManyField(related_name='products', to='shop.Category')),
            ],
            options={
                'ordering': ('chinese',),
            },
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together=set([('id', 'slug')]),
        ),
    ]
