# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ico',
            field=models.ImageField(upload_to=shop.models.Product.ico_path),
        ),
    ]
