# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='快递公司')),
                ('name', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='英文名称')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('url', models.URLField(max_length=300, verbose_name='官方网站')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cost_misc_kg', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='杂货/kg')),
                ('cost_milk_kg', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='奶粉/kg')),
                ('cost_box', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='箱子/个')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=20, verbose_name='收货人')),
                ('payer', models.CharField(blank=True, max_length=20, verbose_name='下单人')),
                ('phone', models.CharField(max_length=15, verbose_name='收货人电话')),
                ('address', models.CharField(max_length=100, verbose_name='收货地址')),
                ('total_expense_aud', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总成本(AUD)')),
                ('total_expense_rmb', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总成本(RMB)')),
                ('total_price_rmb', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总售价(RMB)')),
                ('total_price_aud', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总售价(AUD)')),
                ('fx_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='汇率(1AUD=)')),
                ('track', models.CharField(blank=True, max_length=20, verbose_name='快递单号')),
                ('track_result', models.CharField(blank=True, max_length=100, verbose_name='快递状态')),
                ('message', models.TextField(blank=True, max_length=100, verbose_name='客户留言')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('delivered_date', models.DateField(blank=True, null=True)),
                ('original', models.PositiveIntegerField(default=0)),
                ('courier', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='couriers', to='orders.Courier', verbose_name='快递公司')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_rmb', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='售价RMB')),
                ('price_aud', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='售价AUD')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('expense_aud', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='成本AUD')),
                ('expense_aud_card', models.CharField(choices=[('CN', '中国'), ('OZ', '澳洲')], default='CN', max_length=2, verbose_name='AUD来源')),
                ('expense_rmb', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='成本RMB')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.Product', verbose_name='产品')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('CO', '快递单'), ('DP', '发货照')], default='DP', max_length=2, verbose_name='图片性质')),
                ('image', models.ImageField(blank=True, upload_to='DISPATCH/%Y%m')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='orders.Order')),
            ],
        ),
    ]
